### ISSUE TITLE
[FEATURE] Embedded Gnome Layouts Switcher

### ISSUE THREAD

**Issue by oguzkaganeren** [oguzkaganeren/manjaro-starter#10]
It will be challenging to develop. CLI command can run with Rust, maybe I will go with this.

**Comment by yochananmarqos** [comment]
@Chrysostomus

**Comment by Chrysostomus** [comment]
Okay, so we need cli interfaces for gls.

**Comment by oguzkaganeren** [comment]
Added button to open gnome layout switcher for now.
