### ISSUE TITLE
[Bug][Minor] Default language not selected correctly

### ISSUE THREAD

**Issue by oguzkaganeren** [oguzkaganeren/manjaro-starter#103]
When open settings window for the first time, English language should be selected, but it selected as Deutsche.

**Comment by dai5m5iq** [comment]
@oguzkaganeren thinking of putting English on top the list again in i18n.ts since it's default and most used language, after that in alphabetical order. 
This bug would need a fix regardless anyway. 

´´´
const resources = {
  English,
  Deutsch,
  Polski,
  Turkce,
};
´´´

**Comment by oguzkaganeren** [comment]
I can handle easy way, no need to change the resource list order.

**Comment by oguzkaganeren** [comment]
It is not happened on my side, but it reproduced on live. Anyway, I applied some changes. We will see if it works.

**Comment by dai5m5iq** [comment]
@oguzkaganeren I think you might need to delete .config files to reproduce again. 🤷🏻‍♂️

**Comment by oguzkaganeren** [comment]
Yeah, I did, but now I released I forgot to delete .local/share folder. Now I reproduce it.

**Comment by oguzkaganeren** [comment]
i18n.language get system language code like en-us, tr-tr etc. I have to spend time on it. For now, I cover only en-us.
