### ISSUE TITLE
Current Release Notes not being fetched

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#1068]
The release notes link on the start page of Manjaro Starter is not updated with the current version of 23.x. It still displays release notes version 22.

1. Start Manjaro Starter
2. Click on 'Release Note'
3. Release Notes of version 22 is displayed

System
 - Manjaro Unstable branch
 - Desktop: KDE Plasma 5.27.10 on Wayland
 - Manjaro Starter Version 0.32.6

**Comment by yochananmarqos** [comment]
Can't reproduce, it shows 23.1.2 Vulcan for me. You should have `manjaro-release` 23.1.2-1 installed and `lsb_release -a` should show the Release is 23.1.2.

**Comment by dai5m5iq** [comment]
Update after Mark's message: 
```
lsb_release -ad                                                                                          ✔ 
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        23.1.3
Codename:       Vulcan
```
![image](https://github.com/oguzkaganeren/manjaro-starter/assets/111610689/6a5fe58e-44ce-40cc-b1ac-11b08cb20b15)

**Comment by yochananmarqos** [comment]
I deleted my comment as I initially misunderstood the issue.

**Comment by oguzkaganeren** [comment]
Actually, it is worked as static file because there is no release file on the system. Maybe I can get it from forum releases category when deploy the project or manjaro can put it in /etc/lsb-release. For a now, I've changed the static file according to hello release file. 874e174d32274029cddd66e0fca51951e4f53bc0

**Comment by yochananmarqos** [comment]
@oguzkaganeren It would be better to pull it from [Hello](https://gitlab.manjaro.org/applications/manjaro-hello/-/blob/master/data/pages/en/release).
