### ISSUE TITLE
Some icons missing at package explorer

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#1069]
For some packages the icon is missing at package explorer page and only displays an @ sign. 
Most likely an issue with icon pack I think. 

**To Reproduce**
1. Start Manjaro Starter
2. Go to package explorer page
3. Icons missing for e.g. Firefox, Epiphany, Spotify-launcher

Screenshots
![image](https://github.com/oguzkaganeren/manjaro-starter/assets/111610689/96fcbf41-fe69-4279-b9eb-ab2217be5ccd)

System
    Manjaro Unstable branch
    Desktop: KDE Plasma 5.27.10 on Wayland
    Manjaro Starter Version 0.32.6

**Comment by yochananmarqos** [comment]
@oguzkaganeren Spotify is still missing:

![image](https://github.com/oguzkaganeren/manjaro-starter/assets/5437803/037de72a-8137-486e-9271-eb68c0ccd982)

**Comment by oguzkaganeren** [comment]
16cde2a23a2b1ad74fc835464c093883c3f822eb
