### ISSUE TITLE
Cannot click and drag window

### ISSUE THREAD

**Issue by yochananmarqos** [oguzkaganeren/manjaro-starter#113]
See #54. It was supposedly fixed, but obviously it is not. There seems to be a 1 pixel margin at the top that allows clicking and dragging.

EDIT: This is happening on GNOME and Artem also has the issue on KDE.

**Comment by dai5m5iq** [comment]
In Kde ist ok, I can move the window, the titlebar is rather small though.

**Comment by oguzkaganeren** [comment]
I can increase the height of the area that is able to drag. Is that acceptable? And What do you think the dragging area should be a different color or the same as the header? @yochananmarqos @dai5m5iq

**Comment by yochananmarqos** [comment]
I think it should be the same color as the header.
