### ISSUE TITLE
No dynamic text size adjustment for button (and headers) elements?

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#119]
When text is longer the text does not dynamically adjust in font size to fit the button element. One other limitation due to layout, e.g. 3 elements in one row as shown below have to fit a minimum page size of 800x600. 

Shall the text not be dynamically adjust in size? (Maybe can use em instead of px.)

I am probably going to adjust the German translation in due time because text is too long sometimes. (German language complicated :)) )

![image](https://user-images.githubusercontent.com/111610689/207762083-4d4b70a2-e56f-4e28-aea4-95dd77ec8611.png)
![image](https://user-images.githubusercontent.com/111610689/207762605-88148ae2-9d75-4ae2-8d42-5f83ffeb7d3d.png)

**Comment by oguzkaganeren** [comment]
I fixed buttons for now. I am going to change the design on the Configuration page. Likewise, I will care about headers.
