### ISSUE TITLE
[idea] Include inxi support button to config page

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#120]
Include a button on the configuration page (or whereever feasible) to either jump off to terminal or return terminal output back to application (log pop up) and show the result of command: 

`inxi --admin --verbosity=7 --filter --no-host --width`

Just an idea to facilitate forum support, might diverge from initial aim of the application.
@yochananmarqos Would that be something useful?

**Comment by yochananmarqos** [comment]
I'd say that's a bit out of scope for Starter. 

Besides, we already have that functionality with Stefano's `manjaro-log-helper`:

![image](https://user-images.githubusercontent.com/5437803/207937460-b9eb7bad-7da5-48f1-8b46-83f61664970b.png)

**Comment by dai5m5iq** [comment]
That's ok. It wouldn't provide much benefit anyway.
I close the issue.

**Comment by dai5m5iq** [comment]
Closed
