### ISSUE TITLE
[FEATURE][Major] Add live mode(installer button and removing some settings on live)

### ISSUE THREAD

**Issue by oguzkaganeren** [oguzkaganeren/manjaro-starter#124]
The hello handled it with checking
"live_path": "/run/miso/bootmnt/manjaro",
"installer_path": "/usr/bin/calamares",

**Comment by yochananmarqos** [comment]
The command needs to be `calamares-pkexec`, not `calmares`.

**Comment by oguzkaganeren** [comment]
Do you mean run calamares with pkexec or is there a command like calamares-pkexec ? @yochananmarqos

**Comment by yochananmarqos** [comment]
Sorry, was going from memory. It's actually `calamares_polkit`. See the [desktop file](https://gitlab.manjaro.org/applications/calamares/-/blob/development/data/calamares.desktop#L11).

**Comment by oguzkaganeren** [comment]
Reopen the issue to hide some parts on live.

**Comment by oguzkaganeren** [comment]
Added badge near of app version number, 
The kernels tab is hidden on live,
Manjaro Installer button already added (just improve code).
