### ISSUE TITLE
Join Mailing List button improvement

### ISSUE THREAD

**Issue by yochananmarqos** [oguzkaganeren/manjaro-starter#13]
Currently the button goes to manjaro.org. Unless users scroll to the bottom or search the page, they'll never know how to actually find the mailing lists.

This link jumps to the bottom of manjaro.org highlighting the MAILING LISTS section:

https://manjaro.org/#:~:text=Team-,MAILING%20LISTS,-Development

Problem is, that link will only work in Chromium based browsers. It does not work with Firefox.

@codesardine Maybe a tag to link to that area?

**Comment by codesardine** [comment]
Just link directly to the mailing list.
https://lists.manjaro.org/mailman/listinfo/manjaro-dev

**Comment by yochananmarqos** [comment]
Oh right. Well, it would be this link: https://lists.manjaro.org/mailman/listinfo
