### ISSUE TITLE
[Idea] One-page design can be good to avoid page scrolling too much

### ISSUE THREAD

**Issue by oguzkaganeren** [oguzkaganeren/manjaro-starter#138]
Not sure how to apply it on the software page (maybe some tabs), but it should be better if we apply it on the configuration (Each page should show only one config or group some configs). I will try some sub steps on the configuration page.

**Comment by oguzkaganeren** [comment]
![image](https://user-images.githubusercontent.com/5963437/208717173-ad3098ad-386c-4466-86a7-a0848df982e1.png)
![image](https://user-images.githubusercontent.com/5963437/208717272-99b9adf0-9db0-425d-844f-6f5a30663e29.png)
I am working on a configuration page. What do you think tabs on it? And also I am going to add some information for some settings. @yochananmarqos @dai5m5iq

**Comment by dai5m5iq** [comment]
Looks nice and is probably more intuitive from user perspective. Similar to calamares navigation. 
Will have to try and test it in real time I guess. 
Maybe you can introduce a layout switch (current vs new tabbed) for the interim development if it isn't too much work for you. It's greta, thanks for the time and effort 🙏.

**Comment by oguzkaganeren** [comment]
> Maybe you can introduce a layout switch (current vs new tabbed) for the interim development if it isn't too much work for you. 

It is a good idea, but it is early to do it. When we define or adopt some design strategies, it will be fit. BTW, thank you for your positive feedbacks and your contributions.

**Comment by dai5m5iq** [comment]
You are welcome! I am glad that I was able to help a little bit with my input. 

For the layout switch it's not so important I think. The tabbed design is a good idea in my view. 
However, it's only my opinion. I take whatever the Manjaro team decides. Generally speaking, simple is good and easier. So let's see.

**Comment by oguzkaganeren** [comment]
Okay guys, we have huge design changes on 0.12 version. There can be some bugs. If you find any, let me know. And also, I would be glad your feedback.

**Comment by dai5m5iq** [comment]
Looks nice and more compact than before. Some issues reported, that's normal.
The major drawdown is less content space now due to side navigation. Something solvable.
Also the question is whether side navigation should be standalone or part of prev/next action. 
Package explorer needs some adjustments. The navigation list might be a bit too long.
More feedback from the gnome side is appreciated.
