### ISSUE TITLE
v0.12 Can't navigate/scroll packages (slider)

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#158]
On the software packages page the slider (if still in place?) does not scroll the packages to the left when there is more packages available. 
Also there is no option to manually navigate or scroll between packages.

**Comment by oguzkaganeren** [comment]
I removed the auto scrolling, it caused some flickering (actually I didn't try it with new design yet, I might add app setting to be able to enable-disable it). You should be able to scroll when dragging left or right while clicking on the area. Maybe I should add tips about that. Also, if possible, mouse scrolling support.

**Comment by dai5m5iq** [comment]
Yes, dragging left/right with click works. Using touchpad and 2-finger didn't do anything, which normally does. 
May it be possible to add some arrow navigation on the left and right ends?

**Comment by oguzkaganeren** [comment]
I added left-right button if package count grater than two, for a now mouse scroller doesn't work, but I will handle it in the future.
