### ISSUE TITLE
v0.12 Maximizing the application window at packges page moves navigation out of screen

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#159]
When maximizing the application window at the software packages page the subnavigation at the left side moves out of the screen and cant be used anymore. 
Likewise, the box elements for each package is becoming bigger than it should be.

**Comment by oguzkaganeren** [comment]
Can you share the screenshot about that to be sure what I understand?

**Comment by dai5m5iq** [comment]
This is a printsreen of the maximized window. 

![image](https://user-images.githubusercontent.com/111610689/209345344-385d4240-e49a-4ef6-9752-e9c504161d6f.png)

**Comment by oguzkaganeren** [comment]
I hope it will be fixed with 12.1 version.
