### ISSUE TITLE
v0.12 Content does not fit when resizing down the application window

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#160]
This was my biggest concern with tabbed layout, since I know it from old webdesign with fixed px declarations:
When resizing the window down to lowest possible 800x600px the content does not fit anymore, since it's not really responsive content. The subnavigation on the left moves partially out of the application window.

**Comment by oguzkaganeren** [comment]
Ah, I will fix it.

**Comment by oguzkaganeren** [comment]
Fixed on 12.1 version.

**Comment by dai5m5iq** [comment]
@oguzkaganeren with other languages e.g. when text is longer there is still some content space issues at 800x600 on the left and on the right side of the application window.

![image](https://user-images.githubusercontent.com/111610689/209454868-52f306e3-b251-43aa-bad4-1b6f12a54b0b.png)
