### ISSUE TITLE
v0.12 [Idea] Next button may navigate through subnavigation before moving to packages explorer

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#162]
I think it would make sense if clicking the "Next" button walks the user through all of subnavigation (Mirrors, Updates, Kernel, Settings) at the system configuration page before it proceeds to packages explorer. 
Currently Next goes directly to packages explorer. 

Remark: This should not be the case at the package explorer page. The user should manually select software category because the list is long. 

Remark 2: This request might conflict with each other.  A unified and consistent navigation approach across all pages is preferable. 

! To be discussed what's the best approach. Feedback appreciated!

**Comment by oguzkaganeren** [comment]
Actually, I thought same, but not sure to connect tabs to stepper. Okay we have now not too many tabs on configuration page but in the future it can be increased. People can also be thought that each page needs attention. I don't want to push them the idea. The tabs should be thought like categories. Of course, we can add a warning to inform them about not forgetting to walk other tabs when clicking the next button if they focused on the first tab.

**Comment by dai5m5iq** [comment]
Let's keep it simple for the moment and we leave it as it is. The user always can use <kbd>Prev</kbd> to go back or start over again at the end. No harm done. I such case also no warning needed. 
In any case you can implement guided navigation later.
