### ISSUE TITLE
[Feature] Add app changelog to app settings

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#180]
Currentlyy the app changelog only shows as popup once with a new version. No way to recall it later. 
It would be nice if changelog can be added to app settings, somewhere below the app version number, or maybe with a link by click on the version number at the lower left corner of the app, or even both. Thanks.

**Comment by yochananmarqos** [comment]
I think it should not be displayed at all and instead be available via a button in the settings menu.

**Comment by dai5m5iq** [comment]
@oguzkaganeren 2 small things to add here:
1) as Mark mentioned before the popup with changelog should not be displayed (might be intimidating at first). You maybe remove this feature since we have changelog now in add settings menu. 
2) Changelog translation seems double now in en.json, once as "appChangelog" and once as "changelog". Is this correct?:
 ```
       "appChangelog": "App Changelog",
        "live": "Live",
        "liveTooltip": "You are using Manjaro Live version. Therefore, some configurations can not be worked on Manjaro Starter.",
        "offline": "Offline",
        "offlineTooltip": "Please check your internet connection. Some functions can not be used when you are offline.",
        "changelog": "Changelog",
```

**Comment by oguzkaganeren** [comment]
https://github.com/oguzkaganeren/manjaro-starter/pull/195
