### ISSUE TITLE
GUI issues

### ISSUE THREAD

**Issue by yochananmarqos** [oguzkaganeren/manjaro-starter#19]
I just built it from the latest commit a658e3f:

![Screenshot from 2022-08-02 08-38-38](https://user-images.githubusercontent.com/5437803/182401928-33ca9dae-8909-4bfe-a683-f1368bb5cb3e.png)

**Comment by oguzkaganeren** [comment]
Sorry, I fixed it, but it was not pushed. Now it should be fixed.
