### ISSUE TITLE
[Feature] Progress bar for installation process

### ISSUE THREAD

**Issue by oguzkaganeren** [oguzkaganeren/manjaro-starter#192]
When an update or installing, we should show some progress bar. I am not sure if it is possible but I will search for it.

**Comment by dai5m5iq** [comment]
It would be good to have a progress bar because right now it's not clear if installation is still going on (e.g. with kernels). I mentioned something similar in a previous report.
Similarly it may be beneficial to have a 'cancel' installation option. Thanks.

**Comment by oguzkaganeren** [comment]
Before this, first I have to do https://github.com/oguzkaganeren/manjaro-starter/issues/196

**Comment by oguzkaganeren** [comment]
Note for me: put child processes in a state, cancel button calls the child process to kill.

**Comment by oguzkaganeren** [comment]
I cannot find any solution to show a correct progress bar(percentage value).
