### ISSUE TITLE
[Feature] Sync terminal view

### ISSUE THREAD

**Issue by oguzkaganeren** [oguzkaganeren/manjaro-starter#196]
Before add a progress bar for installation or updating, I am going to add a terminal as sync to show terminal outputs (it's going to look like pamac gui terminal window). Because, I don't know how to increase percentage of progress bar. Now, our installation output popup works as asynchronously, first I convert them to sync.

**Comment by dai5m5iq** [comment]
Pamac also has a progress bar at the bottom.
