### ISSUE TITLE
[Feature] Make "Update directly" inactive when there are no updates available

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#201]
Not sure if this can be implemented with current state. 
Manjaro-Starter checks for updates in the background and reports how many updates are available. 
If there are no updates available (majority case on stable branch) the function of "Update directly" should be made inactive, possibly with a hint that there are no updates available at this moment.

Unless this function is meant to always perform an update regardless of available updates such logic would be more consistent.
@yochananmarqos Your opinion on that feature is appreciated since you know more about pamac. Thanks.

**Comment by oguzkaganeren** [comment]
Maybe we can rename it as "Check for update" when there is no update. I am not sure `pamac checkupdates` use the refresh databases, but `pamac update `do.

**Comment by dai5m5iq** [comment]
I think Manjaro Starter shouldn't be a replacement of pamac considering the intended short time use for onboarding new users with a fresh system installation

**Comment by oguzkaganeren** [comment]
In this view, we can remove the direct update button? Maybe user can learn how to update with pamac if only we keep pamac gui update button. Thus, we don't need to consider the background processes. This is on your call.

**Comment by dai5m5iq** [comment]
The functionality there is quite useful and has its validity. After a fresh installation of Manjaro the user will be greeted by Manjaro starter and he can update the system directly when there are updates. So yes, this makes sense as it simplifies the onboarding process. Later the user will have to learn about pamac updates (without the starter). 
In normal cases Manjaro starter is not used anymore for updates. That's my understanding. 

The question now is what's better: removing a functionality and limiting potential application bugs or keeping the functionality but risking performance issues and additional error causes?

Personally I would keep it there, unless the maintenance costs for potential bug fixing and performance issues exceed the benefits of having it.

Sorry for the long thought process ;).

@yochananmarqos

**Comment by oguzkaganeren** [comment]
Don't think performance issue. Until fix the issue, we hide it temporarily.  BTW, we would be good if we have git package as manjaro-starter-git to easily test it before releasing it. Especially, it helps us on live iso (otherwise I have to install the dev environment on live).

**Comment by dai5m5iq** [comment]
I agree with hiding it for the moment. It's not super necessary, there is the pamac GUI update available instead until the rest is fixed and tested thoroughly.

Good point also with the git package! It would be helpful to test new features separately from the live version.

**Comment by yochananmarqos** [comment]
> If there are no updates available (majority case on stable branch) the function of "Update directly" should be made inactive

@dai5m5iq I agree with everything but the bit in parenthesis. Depending on how long ago the ISO on the download page was released, there could be hundreds of updates.

Manjaro Starter is only for initial onboarding. Users should be pushed toward the tools they should be using from that point onward. Handy buttons for updating mirrors and checking for initial updates is all that is needed.

New users will not know what Pamac is. The menu item is Add/Remove Software, that's all they will see right away.

@oguzkaganeren VCS packages are not possible in the repos as all packages are static. You'll need to maintain your own PKGBUILD to pull from the latest commit.

I've just [switched to using a commit](https://gitlab.manjaro.org/packages/extra/manjaro-starter/-/commit/983324f32fb3694c78f2b974ce3c014a3903744c) instead of the release tarball in the PKGBUILD. That way, you can just change the commit to test locally.

**Comment by dai5m5iq** [comment]
@yochananmarqos yes most likely there will be updates after a fresh installation. Once the update is performed on starter it will take ~3 weeks on stable branch for new updates. That's past Manjaro starter's usage.

That's why I would keep the functionality of the direct update button limited. It should work as expected and basically just have an active/inactive (on/off) status, but shouldn't incorporate full pamac features like checking for new updates everytime the button is pressed.

**Comment by oguzkaganeren** [comment]
For a now, I hide the direct update button. I understood we should redirect the user to how to use other tools on Manjaro. We can improve what we have about that. 

The purpose of the features is the first thing first after installation. If we have tools that are before developed any feature, we should show them to users. Of course, we need to have integrated features, but they are mostly developed ones before without GUI.

These are what I understood from the comments. And I will keep features that fit these.
