### ISSUE TITLE
[FEATURE] Show package icon instead of the default icon 

### ISSUE THREAD

**Issue by oguzkaganeren** [oguzkaganeren/manjaro-starter#21]

**Comment by yochananmarqos** [comment]
Wouldn't it be easier to just depend on `paprius-icon-theme` rather than doing this?

**Comment by oguzkaganeren** [comment]
@yochananmarqos not sure, because Tauri only access some folders https://tauri.app/ko/v1/api/js/modules/path/ 
If we add a dependency, then we have to access usr/share/icons folder, but we don't do it now (that because maybe some security prevention)
