### ISSUE TITLE
Cancel package installation returns successful installation message

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#214]
After successfully canceling a package installation it returns a "Installed successfully" message as popup. 

![image](https://user-images.githubusercontent.com/111610689/210308403-95c08ff5-fccc-4561-bbc4-7d32d0579d0f.png)

**Comment by dai5m5iq** [comment]
The thing is, it's quite difficult to cancel the installation because it goes very fast and once the package is downloaded and you try again it just performs the installation. 
I was trying with a bigger package. Please try with blender and see if you can cancel right after supplying the password.

**Comment by oguzkaganeren** [comment]
okay, I will try it later
