### ISSUE TITLE
[Bug] Add update check text

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#231]
On system configuration page > Updates when requesting the page it performs pamac checkupdates in the background and displays a loading progress icon only. It would be beneficial if there is some colored text next to the loading progress icon saying "Checking for updates". 

![image](https://user-images.githubusercontent.com/111610689/211241944-1bcde16f-1392-43c5-bca1-2ceb8e55d724.png)

![image](https://user-images.githubusercontent.com/111610689/211250910-fc814156-823f-450a-836a-18a670967ee1.png)

**Comment by dai5m5iq** [comment]
@oguzkaganeren 
Looks nice now, thanks!
Though one remark: We have a language translation element for checking but I don't see one for "Your system is up to date." or "xx updates availabe". Should we make it consistent?
`        "checkingForUpdates": "Checking for updates"`

![image](https://user-images.githubusercontent.com/111610689/211477356-510009cd-b9f1-40da-978d-8b372b54b64e.png)

**Comment by oguzkaganeren** [comment]
Actually, "Your system is up to date." and "xx updates availabe" are coming from pamac. I don't touch them, maybe your system language effect it.

**Comment by dai5m5iq** [comment]
Yes I am using English as my system language, that's why.
