### ISSUE TITLE
[Feature] Translated Manjaro-starter in French

### ISSUE THREAD

**Issue by Tuxman2** [oguzkaganeren/manjaro-starter#270]
Hello,

I translated Manjaro Starter in French, but I don't know if all my translations are good. If someone in the Manjaro Team can check my translations (of course if someone in the team knows the French language), it will be great. I tried the 'yarn tauri dev' command but I've got an error displayed in the terminal. I don't know how to use the pull request, so I send you fr.json and i18n.ts files here. Can you check it ? 

Thanks in advance for your work and your help.

Regards.

[fr.json.zip](https://github.com/oguzkaganeren/manjaro-starter/files/10466583/fr.json.zip)

[i18n.ts.zip](https://github.com/oguzkaganeren/manjaro-starter/files/10466586/i18n.ts.zip)

**Comment by yochananmarqos** [comment]
> I don't know how to use the pull request

Good time to learn then, eh? 😉 

Please see [About pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)

**Comment by Tuxman2** [comment]
Pull request created.

**Comment by yochananmarqos** [comment]
Something is not right with #284. There are 237 commits and 5,000 files changed. I don't see any commits by you.

**Comment by Tuxman2** [comment]
Ok. I think that it is all right now. It was not easy for me because it was the first time that I made pull request. So, tell me if it is good.

Regards.

**Comment by oguzkaganeren** [comment]
Merged, thank you for all your effort.

**Comment by dai5m5iq** [comment]
@Tuxman2 
Wanted to open an issue at your fork repository but issues are not enabled for it. 
Minor correction to report: translation text for appLogInfo is slighty too long. It overlaps. You can send new pull request with change. Thanks. 

![image](https://user-images.githubusercontent.com/111610689/214070418-d92332e0-181a-489e-aff7-df068baef23f.png)

**Comment by Tuxman2** [comment]
@dai5m5iq: The issue tab is enabled on my fork now. I can't change the translation text for appLogInfo in my case, this is the translation in french for this line. Perhaps oguzkaganeren can allow more words to be displayed.

**Comment by dai5m5iq** [comment]
@Tuxman2 not everything needs literal translation
E.g you could use 
journaux des applications @ ...
journaux des applications à ...
Something like that. Users will know.

**Comment by Tuxman2** [comment]
@dai5m5iq: I do another translation for the line you noticed. Tell me if it is ok.

**Comment by dai5m5iq** [comment]
I'll check with the next version release. Thanks for the fast response!

**Comment by Tuxman2** [comment]
@dai5m5iq: Ok. The new translation is more small. Otherwise, it is good for the rest of the translations ?

**Comment by dai5m5iq** [comment]
@Tuxman2 
it looks fine now. 
Users will let us know if the translations are ok :)). Contentwise I don't speak French so I can't tell but looks fine overall. Thank you! 
For my German translations I had to shorten it also in some areas to no exceed the available space.
