### ISSUE TITLE
[Idea] Translation plugin can be used for the release notes

### ISSUE THREAD

**Issue by oguzkaganeren** [oguzkaganeren/manjaro-starter#313]
https://github.com/teamgantt/react-auto-translate can be used.

**Comment by dai5m5iq** [comment]
According to docs it rquires Google account and API key.
googleApiKey='API_KEY'
They have free quota of something like 200 Euros for private use, otherwise it's a paid service. 
Not sure what Manjaro can get as a business account.

**Comment by oguzkaganeren** [comment]
I'm just looking for others, I don't think use Google services.

**Comment by dai5m5iq** [comment]
Yeah it's quite a dependency to a third party. 

How about Deepl API?

**Comment by oguzkaganeren** [comment]
I tried many APIs but they have some limitation. For now, I close the issue.
