### ISSUE TITLE
[BUG] Lauch at start does not work

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#39]
In application menu the option 'Launch at start' does not work to autostart the application in KDE Plasma.

**Comment by oguzkaganeren** [comment]
I will test it. I guess, KDE uses different folder for auto start.

**Comment by dai5m5iq** [comment]
On a Manjaro Gnome verison in a VM Launch at start did not work either. No .desktop in ~/config/autostart/

**Comment by oguzkaganeren** [comment]
It will be fixed with https://gitlab.manjaro.org/packages/extra/manjaro-starter/-/issues/3 for Gnome. I will look for KDE

**Comment by oguzkaganeren** [comment]
I guess, it works on KDE. @dai5m5iq can you test it with latest version in your free time.

**Comment by dai5m5iq** [comment]
@oguzkaganeren Autostart works on KDE and also working as expected in Gnome (43 now). 
It creates an entry in ~/config/autostart/
Just wondering why not using /usr/share/applications instead of /urs/lib/
Anyways, it works. Thanks.

**Comment by oguzkaganeren** [comment]
I only access some path with tauri library. Maybe I could use shell command, but resources path can be used in the future.
