### ISSUE TITLE
Context menu actions

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#40]
The applications context menu offers Back, Forward, Stop and Reload. While not sure if it's by design but Back, Forward and Stop are greyed out, only Reload works. 
Tested on KDE Plasma desktop.

**Comment by oguzkaganeren** [comment]
I guess it is integrated with webgtk. I don't want to touch it until Tauri adds new configs about it.

**Comment by dai5m5iq** [comment]
This is ok. It's not a critical or important feature as long as the normal navigation works. 
Postpone this one for later or cancel it when it's not adjustable.
