### ISSUE TITLE
Installing packages from Explorer returns error message

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#41]
When installing additional packages from packages explorer returns /dev/tty error. 
The package does get installed properly but the page does not get updated properly and it shows the application as uninstalled. 
Only after reloading the application the software shows as installed. 
Tested on KDE Plasma desktop. 

```
gparted
Error creating textual authentication agent: Error opening current controlling terminal for the process (`/dev/tty'): No such device or address (polkit-error-quark, 0)
```

![image](https://user-images.githubusercontent.com/111610689/185708620-c326cb3d-5c84-43b0-b2ad-92ecbc0d18e4.png)

**Comment by dai5m5iq** [comment]
Installation of packages updates status correctly now, though still get error message. Is that something on my side? 

![image](https://user-images.githubusercontent.com/111610689/192008403-67da2647-1c21-4d96-8cfe-f8e1244ff014.png)

**Comment by oguzkaganeren** [comment]
> @oguzkaganeren Installation of packages updates status correctly now, though still get error message. Is that something on my side because of polkit?
> 
> ![image](https://user-images.githubusercontent.com/111610689/192008403-67da2647-1c21-4d96-8cfe-f8e1244ff014.png)

Can you try with the terminal using `pamac install --no-confirm --no-upgrade packagename`. If you get the same error, there is a problem on your side otherwise I have to test it on KDE system.

**Comment by dai5m5iq** [comment]
No issue with terminal installation:

```
pamac install --no-confirm --no-upgrade simplescreenrecorder                                                  100 ✘  18s  
Preparing...
Resolving dependencies...
Checking inter-conflicts...

To install (1):
  simplescreenrecorder  0.4.4-1    community  

Total installed size: 3,9 MB

Checking keyring...                                                                                                                 [1/1]
Checking integrity...                                                                                                               [1/1]
Loading packages files...                                                                                                           [1/1]
Checking file conflicts...                                                                                                          [1/1]
Checking available disk space...                                                                                                    [1/1]
Installing simplescreenrecorder (0.4.4-1)...                                                                                        [1/1]
Running post-transaction hooks...
Arming ConditionNeedsUpdate...                                                                                                      [1/4]
Refreshing PackageKit...                                                                                                            [2/4]
Updating icon theme caches...                                                                                                       [3/4]
Updating the desktop file MIME type cache...                                                                                        [4/4]
Transaction successfully finished.
```

**Comment by dai5m5iq** [comment]
Tested this on Manjaro Gnome version in a VM and indeed does not bring up this error message when installing a package.

**Comment by dai5m5iq** [comment]
@oguzkaganeren Should we reopen this report again?

**Comment by oguzkaganeren** [comment]
I tested it on KDE system and reproduced it. I guess, we have some permission problems. When I open Manjaro starter with sudo then I don't get the error. I will continue to look for a solution.

**Comment by yochananmarqos** [comment]
This is an upstream problem. DO NOT use `sudo` with `pamac`. I will not push 0.4.2 because of this.

**Comment by dai5m5iq** [comment]
I agree with Mark, no sudo with pamac. 
@yochananmarqos upstream you mean tauri or polkit ?

**Comment by oguzkaganeren** [comment]
@yochananmarqos I reverted it. `Sudo` means `pkexec` in here, but I will look different solution.

**Comment by yochananmarqos** [comment]
@dai5m5iq I mean with Pamac itself.

**Comment by oguzkaganeren** [comment]
Logs are not listed on the popup anymore. Command history is used. I will test it on KDE, what is the status on command history.

**Comment by oguzkaganeren** [comment]
It doesn't appear anymore.
