### ISSUE TITLE
[Feature] Provide access to some logs 

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#42]
The application offers many functions to be executed, however, when doing so there are no logs to trace what actually went wrong, in case of errors. For new users this might be intimidating. 
There is ~/.config/com.manjaro.starter/logs/manjaro-starter.log as application log, it remains empty. 
Mhwd, pacman, pamac logs might be incorporated. 
Tested on KDE Plasma desktop.

**Comment by dai5m5iq** [comment]
@oguzkaganeren installed a kernel and log in ~/.config/com.manjaro.starter/logs/manjaro-starter.log gets filled now. It renames older logs with a timestamp and creates new ~/.config/com.manjaro.starter/logs/manjaro-starter.log. That's great. 
Not sure at which other actions the log is triggered.

**Comment by oguzkaganeren** [comment]
I fixed it(https://github.com/oguzkaganeren/manjaro-starter/commit/99dfe9fab74deee514cec0ed1c0c87cb87c59df5). It only works for installations and updates for now.

**Comment by dai5m5iq** [comment]
@oguzkaganeren Should there be a button somewhere to access the log or should it be left to the user to check in user directory? 
It would be a new feature. Considering that the application usage is minimal I think a button might not be required. 
What do you think?

**Comment by dai5m5iq** [comment]
> I am thinking detailed application menu(instead of a drop-down menu at the right top), maybe we can put it somewhere.

Yes, within application menu should be fine. Is the question of how to handle/ integrate  the older logs which it creates with  a timestamp, as far ass I can see. Maybe I am wrong here.

**Comment by oguzkaganeren** [comment]
Added only path to settings popup, no need to open with an editor.
