### ISSUE TITLE
Software explorer item card display error with resized window

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#431]
**Describe the bug**
First item cards at software explorer page are not displayed fully with resized down application window after using arrow navigation.  

**To Reproduce**
1. Go to software explorer page. It will start with browser category.
2. At browser category use right arrow navigation to navigate between packages
3. Resize application window down to lowest size
4. Use left arrow navigation to navigate back to first package of category
5. Error: First item card is not displays fully and can't be navigated further left. 

**Expected behavior**
All software item cards are displayed fully even with downsized application window.

**Screenshots**
![image](https://user-images.githubusercontent.com/111610689/219904250-f527b32e-d97e-493a-b1ff-570572f38c57.png)

**Comment by oguzkaganeren** [comment]
I guess, I have to change keen-slider (third part slide component). Because it uses overflow hidden, it affects some designs. And also this problem.

**Comment by dai5m5iq** [comment]
Can keen slider be set as carousel or loop? Meaning that after the last package it loops back to first?

**Comment by oguzkaganeren** [comment]
Yep, but I am not sure that it would be good? https://keen-slider.io/examples

**Comment by dai5m5iq** [comment]
It's not a critical bug anyway. We maybe give it some time to think about a solution. Would love to see everything responsive.

**Comment by dai5m5iq** [comment]
Cards still can be moved manually to the beginning with mouse/touch-pad. It's only the left arrow which disappears too early and therefore no navigation anymore with left arrow.

**Comment by oguzkaganeren** [comment]
I think, there is no problem anymore. If it is, you can reopen the issue.
