### ISSUE TITLE
[Feature] Provide tooltips on hover

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#45]
For newbies it's probably unclear what all these buttons do..
Provide tooltips with some basic explanations for buttons, actions, and lables.

**Comment by oguzkaganeren** [comment]
https://github.com/oguzkaganeren/manjaro-starter/issues/60

**Comment by dai5m5iq** [comment]
@oguzkaganeren Not sure if #60 is meant to provide what I reported with this request. 
Basically I meant tooltips on hover for the buttons that installs kernels, packages, updates the system, or any link etc. 

When placing the mouse over the buttons there should be some tooltip on hover saying for example: `Install Chromium'; or Install 'Linux Kernel 6.0'; or 'Discover Software online' ..etc.
