### ISSUE TITLE
Manjaro Starter on Wayland with KDE Plasma 5.27

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#460]
**Describe the bug**
Manjaro Starter on Wayland with KDE Plasma 5.27 comes with title bar and very small screen resolution. 
It might be too early to test this in Wayland. Some people use their system in Wayland.  

**To Reproduce**
1. Log in to KDE Plasma with Wayland session
2. Start Manjaro Starter
3. Check Manjaro Starter application 

**Expected behavior**
Application looks and behaves same as with X11

**Screenshots**
![image](https://user-images.githubusercontent.com/111610689/221333665-876b15a9-0a46-45f9-8e81-0a0da77d8a64.png)
![image](https://user-images.githubusercontent.com/111610689/221333699-b96c5687-9f3b-4145-9f26-368995331838.png)
![image](https://user-images.githubusercontent.com/111610689/221333936-8854962e-5e7d-43f4-93f8-1e56f2c9f6cb.png)
![image](https://user-images.githubusercontent.com/111610689/221333874-069da25a-3a19-412f-89f5-db75457ca03f.png)

**Desktop (please complete the following information):**
 - OS: Manjaro 22.0.4
 - KDE Plasma 5.27.1 using Wayland
 - Manjaro Starter 0.31.0

**Additional context**
Maybe needs confirmation from other users if can be reproduced on other machines.

**Comment by dai5m5iq** [comment]
Noticed that Gnome/GTK application style isn't applying correctly on Wayland for me. Also Pamac and other GTK apps do not apply Breeze GTK (breeze-gtk) theme or any other downloaded GTK theme from store. Looks like a KDE bug. Will investigate further.

**Comment by oguzkaganeren** [comment]
Maybe, you found a tauri bug. I will check it in my free time.

**Comment by dai5m5iq** [comment]
Just tested in a VM on testing branch with Plasma 5.26.5 and Manjaro Starter 0.29.0 using Wayland session and it looks normal as expected, same as in X11.
Will perform an upgrade in the VM from unstable branch and then see what happens. Thanks.

**Comment by dai5m5iq** [comment]
I wasn't fully able to reproduce the complete error. It's not a tauri bug. Must be something with my config at my Plasma installation. 

- Starter has titlebar in Wayland
- Starter shows normal resolution 
- Gtk style can be changed to <> breeze-gtk and is being applied to other apps like Pamac accordingly

Steps performed:

1. Switched to unstable branch
2. Upgraded Manjaro Starter to 0.31 from 0.29 using Plasma 5.26.5 and Wayland>> Manjaro Starter looks ok
3. Performed full system update to Plasma 5.27.1 >> Manjaro Starter still looks the same with extra titlebar, elswise ok
4. Downgraded Manjaro Starter again to 0.29 >> Manjaro Starter still looks the same with extra titlebar, elswise ok

**Comment by dai5m5iq** [comment]
Resolution error solved: reinstalled breeze-gtk package and now seems normal. 

Only issue left is the extra titlebar on top of the app.

**Comment by oguzkaganeren** [comment]
You can close it. If I find something, I apply it.

**Comment by dai5m5iq** [comment]
Issue solved.
