### ISSUE TITLE
Bump version and PKGBUILD version differs

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#53]
Minor adjustment: Bump version and PKGBUILD version differs.
https://gitlab.manjaro.org/packages/extra/manjaro-starter/-/blob/master/PKGBUILD
```
pkgver=0.0.1.192
_commit=61d637e015f8116c75b41d9a5cbfafc9b24408cd
```
```
Manjaro Starter
0.0.1-189
```

Maybe bump version one more time or ahead of commits or adjust pkgbuild. Thanks.

**Comment by yochananmarqos** [comment]
@dai5m5iq No, it wouldn't. I'm using the release tag commit. The version in the `package.json` needs to be bumped before the release is tagged.

**Comment by dai5m5iq** [comment]
@yochananmarqos 
> I'm using the release tag commit.

Yes I saw that. So version bump comes before release tagging.

**Comment by oguzkaganeren** [comment]
I try to fix on the action. Do not mind last versions. When I complete, I will close the issue.

**Comment by dai5m5iq** [comment]
As feedback for now: current version can almost be shipped in my point of view. Launch at start plus the polkit error when installing packages and text/wording updates may need to be solved before. The rest is optional feature enhancements. It's up to Manjaro team how many of those make sense. Thanks for the fast response!

**Comment by oguzkaganeren** [comment]
I guess it is fixed. I removed manual generated versions. Changed some action libs. And generated 0.0.2. https://github.com/oguzkaganeren/manjaro-starter/releases/tag/v0.0.2
