### ISSUE TITLE
 GUI page reload gets stuck in certain navigation cases same as #46 

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#62]
Same as #46 but this time on the Finish button:

Steps to reproduce:

1. Start program
2. Click <kbd>Next</kbd> until you reach Package Explorer page
3. Important ! : Scroll down on Package Explorer to the very bottom
4. Click <kbd>Finish</kbd> to reach the last page

**Result**: Finish page stays blank and does not refresh it's content

**Remark:** What finally loads the page again is navigating to and activating the application menu on top. This seems to provide a refresh trigger for the page content.

**Comment by yochananmarqos** [comment]
I can reproduce this. However, the page is not actually blank. Scroll all the way back to the top and the content is there.

**Comment by dai5m5iq** [comment]
@yochananmarqos not so on my end with KDE somehow. I can't scroll up. It's just a onepager without scroll.

**Comment by dai5m5iq** [comment]
Yes that's it:     window.scrollTo(0, 0);
