### ISSUE TITLE
React tour tooltip stays on system configuration page after clicking 'Let's begin'

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#65]
The newly introduced React tour tooltip on the Welcome page's 'Let's begin' button stays on system configuration page after it's been clicked.

I see 3 possible ways to overcome this depending on the intended use of the React tour function:

1. Reset the tooltip on every page
2. Leave it active and let the user click it away (least preferred by users I guess). If so, the box around <kbd>Prev</kbd> <kbd>Next</kbd> needs to be adjusted to match in size. 
3. Bring up a separate React tour tooltip for each page, in this case a tooltip explaining the system configuration page. 

![image](https://user-images.githubusercontent.com/111610689/192688703-d781061f-18e9-4b51-9285-02ce72ea4bc6.png)

**Comment by oguzkaganeren** [comment]
I updated it. Hiding tour when clicking the next button.
