### ISSUE TITLE
Scrollbar not visible (in front) with breeze-gtk on KDE Plasma 

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#66]
Noticed that in Gnome environment there is a scrollbar on the right side. 
On KDE Plasma the scrollbar is physically there (I can use it when grabbing it) but not visible when using default breeze-gtk application style. 
Using another GTK application style in system settings the scrollbar shows. 

Could this be due to zIndex? Maybe being defined behind content page?  

Default GTK style top vs. breeze-gtk below
![image](https://user-images.githubusercontent.com/111610689/192832204-a67d4ec9-63b4-4cfd-8e30-809620bbcfa0.png)

![image](https://user-images.githubusercontent.com/111610689/192832559-12f681a6-408d-47ab-9182-be5249ea48ac.png)

**Comment by oguzkaganeren** [comment]
It related GTK style, there is no option for scroll style.
