### ISSUE TITLE
[FEATURE] Launch at start

### ISSUE THREAD

**Issue by oguzkaganeren** [oguzkaganeren/manjaro-starter#8]
It should be like Manjaro hello. Look its source.

**Comment by yochananmarqos** [comment]
Well, do it then. :stuck_out_tongue_closed_eyes:

**Comment by oguzkaganeren** [comment]
@yochananmarqos first I am creating what I to-do list :) then I will.

**Comment by yochananmarqos** [comment]
Sounds like a plan. I was just poking you for fun. 😉

I'm eager to see how it all turns out.
