### ISSUE TITLE
Application misuse with window tiling

### ISSUE THREAD

**Issue by dai5m5iq** [oguzkaganeren/manjaro-starter#80]
Before describing the issue a remark: I doubt the developer can do anything to prevent the following behavior. I report it anyway for being aware of the issue. Feel free to close this bug report without investigating further. 

Issue: 
In KDE you can snap the application window to any window edge and it tiles accordingly to either half of the screen or a quarter of the screen. If the screen is generally small it bypasses the minimum window size of 800x600 and the application becomes unusable, same as described in #37 .
I am aware that this is a rare case with smaller screens and it's a misuse of the application. However, some users might actually have this tiling windows DE. 

I am not sure what a solution could be for it as other applications generally have the same issue if they are not responsive.

**Comment by oguzkaganeren** [comment]
We can try to find a solution when someone has trouble with that. There is nothing to do for now.
