### ISSUE TITLE
[FEATURE] Add MCP support

### ISSUE THREAD

**Issue by yochananmarqos** [oguzkaganeren/manjaro-starter#83]
We should check for [Manjaro Control Panel](https://gitlab.com/LordTermor/msm-ng) first, then look for MSM if MCP is not found.

**Comment by dai5m5iq** [comment]
@oguzkaganeren Does it mean that with MCP there are no button links to install drivers or language packs? Only the <kbd>More Settings</kbd> button?

**Comment by oguzkaganeren** [comment]
@dai5m5iq there is no module CLI on MCP. I created an issue about that https://gitlab.com/LordTermor/msm-ng/-/issues/13
Maybe I can implement embedded something.

**Comment by dai5m5iq** [comment]
For the KDE version of mcp-kcm the modules can be called with kcmshell5. However, that does not help you overall, because you can't use mcp-kcm for the starter.
We'll see what's the solution for mcp-qt will be.
Thanks for opening the issue.

**Comment by oguzkaganeren** [comment]
It can be challenged for me, but I will try to add CLI to MCP in my free time.
